"""add_escalations_table

Revision ID: 1263c4b4dc6d
Revises: c2a7d5b9e4f3
Create Date: 2026-08-26 20:50:04.505844
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1263c4b4dc6d'
down_revision: Union[str, None] = 'c2a7d5b9e4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=64), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('rule', sa.Integer(), nullable=False),
    sa.Column('originating_agent', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_claim_id'), 'escalations', ['claim_id'], unique=False)
    op.create_index(op.f('ix_escalations_id'), 'escalations', ['id'], unique=False)
    op.create_index(op.f('ix_escalations_reason_code'), 'escalations', ['reason_code'], unique=False)
    op.create_index(op.f('ix_escalations_severity'), 'escalations', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escalations_severity'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_reason_code'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_claim_id'), table_name='escalations')
    op.drop_table('escalations')
    # ### end Alembic commands ###
