"""add recommendation approval fields

Revision ID: 200d731586ac
Revises: 1263c4b4dc6d
Create Date: 2026-08-26 23:22:59.227302
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200d731586ac'
down_revision: Union[str, None] = '1263c4b4dc6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('action_type', sa.String(length=32), nullable=True))
    op.add_column('recommendations', sa.Column('confidence', sa.String(length=16), nullable=True))
    op.add_column('recommendations', sa.Column('low_confidence', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('recommendations', sa.Column('cited_issue_types', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('secondary_options', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('raw_model_response', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('approval_status', sa.String(length=16), nullable=False, server_default='pending'))
    op.add_column('recommendations', sa.Column('decided_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_recommendations_action_type'), 'recommendations', ['action_type'], unique=False)
    op.create_index(op.f('ix_recommendations_approval_status'), 'recommendations', ['approval_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_approval_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_action_type'), table_name='recommendations')
    op.drop_column('recommendations', 'decided_at')
    op.drop_column('recommendations', 'approval_status')
    op.drop_column('recommendations', 'raw_model_response')
    op.drop_column('recommendations', 'secondary_options')
    op.drop_column('recommendations', 'cited_issue_types')
    op.drop_column('recommendations', 'low_confidence')
    op.drop_column('recommendations', 'confidence')
    op.drop_column('recommendations', 'action_type')
    # ### end Alembic commands ###
